export const uiText = {
  app: {
    fatalErrorTitle: 'Application error',
  },
  topBanner: {
    defaultQuery: 'quiet dreamy piano loop',
    title: 'Music Candidate Space',
    subtitle: 'map-first exploration HUD',
    queryPlaceholder: 'Describe a music idea...',
    search: 'Search',
    candidateCount: (count) => `${count} candidates`,
    noPair: 'no pair',
    noQuery: 'no query',
    resetView: 'Reset view',
    toggleHud: 'Toggle HUD',
    advanced: '',
    theme: '',
    debug: '',
  },
  map: {
    emptyTitle: 'Enter a query to generate a candidate space.',
    emptyHint: 'WASD or arrow keys move the camera. Mouse wheel zooms.',
    loadingQueued: '任务排队中',
    loadingRunning: '正在分析候选空间与生成坐标轴说明…',
    showAxisNote: '显示坐标轴说明',
    hideAxisNote: '隐藏坐标轴说明',
    showHud: 'HUD',
    minimapTitle: 'MiniMap',
    minimapAria: 'Candidate minimap',
  },
  axisFallbacks: {
    xName: '明亮感',
    yName: '張力感',
    xNegative: '陰暗厚重',
    xPositive: '明亮輕盈',
    yNegative: '柔和治癒',
    yPositive: '緊張強烈',
  },
  candidate: {
    title: (rank) => `Candidate #${rank}`,
    ariaLabel: (rank) => `Candidate ${rank}`,
    untagged: 'untagged',
    tooltipHint: 'click to inspect',
    details: 'Details',
    previous: 'Previous',
    next: 'Next',
    playPause: 'Play or pause',
    marks: {
      good: '👍',
      bad: '👎',
      interesting: '❤️',
    },
    downloadMidi: 'Download MIDI',
    midi: 'MIDI',
    fields: {
      candidateId: 'candidate_id',
      rank: 'rank',
      searchScore: 'search_score',
      poolId: 'pool_id',
      embeddingIndex: 'embedding_index',
      pcValues: 'pc_values',
      audioUrl: 'audio_url',
      midiUrl: 'midi_url',
    },
  },
  panels: {
    close: 'Close',
    advancedTitle: 'Advanced',
    debugTitle: 'Debug',
    themeTitle: 'Theme',
  },
  advanced: {
    labels: {
      baseUrl: 'BASE_URL',
      poolId: 'pool_id',
      topK: 'top_k',
      selectN: 'select_n',
      axes: 'axes',
      endpointNList: 'endpoint_n_list',
      pollingInterval: 'polling interval ms',
      showAxisFrames: 'Show X/Y axis labels outside map',
    },
    save: 'Save',
    resetLocalState: 'Reset local state',
  },
  debug: {
    tabs: {
      task: 'task',
      space: 'space',
      artifacts: 'artifacts',
      requests: 'requests',
      events: 'events',
    },
    emptyTask: 'No task yet.',
    emptySpace: 'No space yet.',
    emptyArtifacts: 'No artifacts.',
    metadata: 'Metadata',
    content: 'Content',
  },
  theme: {
    options: [
      { id: 'theme-nord', label: 'Nord Frost' },
      { id: 'theme-dark', label: 'Deep Dark' },
      { id: 'theme-minimal', label: 'Minimal Ice' },
    ],
  },
  errors: {
    audioUnavailable: 'Audio unavailable or failed to load.',
    missingAudioUrl: 'This candidate has no audio_url.',
    audioPlayFailed: 'Audio failed to play.',
    taskFailed: 'Task failed',
    missingSpaceId: 'Task finished without outputs.space_id',
    taskPollingTimeout: (maxAttempts) => `Task polling timed out after ${maxAttempts} attempts`,
  },
};
