export const uiText = {
  app: {
    fatalErrorTitle: '应用错误',
  },
  topBanner: {
    defaultQuery: 'quiet dreamy piano loop',
    title: '音乐创作探索',
    subtitle: '种子 × 空间 × 探索',
    queryPlaceholder: '描述一个音乐想法...',
    search: '搜索',
    candidateCount: (count) => `${count} 个种子`,
    noPair: '',
    noQuery: '',
    resetView: '重置视图',
    toggleHud: '显示 / 隐藏面板',
    advanced: '高级设置',
    theme: '主题',
    debug: '调试',
  },
  map: {
    emptyTitle: '输入搜索提示，生成音乐种子空间',
    emptyHint: 'WASD / 方向键移动视角，鼠标滚轮缩放视角',
    loadingQueued: '任务排队中',
    loadingRunning: '正在分析种子空间与生成坐标轴说明…',
    showAxisNote: '显示坐标轴说明',
    hideAxisNote: '隐藏坐标轴说明',
    showHud: '面板',
    minimapTitle: '小地图',
    minimapAria: '种子小地图',
  },
  axisFallbacks: {
    xName: '明亮感',
    yName: '张力感',
    xNegative: '阴暗厚重',
    xPositive: '明亮轻盈',
    yNegative: '柔和治愈',
    yPositive: '紧张强烈',
  },
  candidate: {
    generatedMix: '后代',
    title: (rank) => `种子 #${rank}`,
    offspringTitle: (rank) => `后代 #${rank}`,
    shortTitle: (id) => `种子 ${id}`,
    offspringShortTitle: (id) => `后代 ${id}`,
    ariaLabel: (rank) => `种子 ${rank}`,
    offspringAriaLabel: (rank) => `后代 ${rank}`,
    untagged: '未标记',
    tooltipHint: '点击查看详情',
    details: '种子详情',
    previous: '上一个',
    next: '下一个',
    playPause: '播放 / 暂停',
    volume: '播放音量',
    marks: {
      good: '',
      bad: '',
      interesting: '',
    },
    downloadMidi: '下载 MIDI',
    midi: 'MIDI',
    fields: {
      candidateId: '种子ID',
      rank: '排名',
      searchScore: '搜索分数',
      poolId: '资源池ID',
      embeddingIndex: '嵌入索引',
      pcValues: '主成分坐标',
      audioUrl: '音频地址',
      midiUrl: 'MIDI 地址',
      parentCandidateIds: '父代种子',
      mixId: '混合ID',
      createdByTaskId: '任务ID',
    },
  },
  mixing: {
    title: '种子混合',
    open: '混合',
    generate: '生成后代',
    generating: '正在生成新的后代片段…',
    clear: '清空',
    remove: '移除',
    emptyHint: '按住 Ctrl 或 Cmd 点击地图上的种子，加入混合。至少选择 2 个种子才能生成后代。',
    sources: '已选种子',
    geometry: '混合位置',
    geometryHint: '拖动调整比例，滚轮缩放',
    weights: '权重',
    settings: '生成设置',
    outputBars: '小节数',
    targetBpm: 'BPM',
    chordProgression: '和弦进行（用逗号分隔，每小节一个）',
    defaultChordProgression: ['C', 'Am', 'F', 'G'],
    chordValid: '和弦进行可用。',
    bpmError: 'BPM 需要在 40 到 240 之间。',
    geneSynthesisTitle: '基因合成',
    expectedGenomeTitle: '预期后代基因',
    harmonySourcesTitle: '和声来源',
    harmonyPreviewHint: '和声采用序列方式生成，将在最终生成阶段解析。',
    parentGenomeStatus: {
      loaded: '详细基因已加载',
      loading: '正在加载详细基因...',
      error: '详细基因加载失败，使用概要信息',
      summary: '概要基因',
    },
    synthesisStatus: {
      summary: '当前为概要级基因预览。',
      error: '部分基因加载失败，显示可用结果。',
      loaded: '父代详细基因已加载。',
      loading: (loaded, total) => `正在加载父代详细基因... ${loaded} / ${total} 已就绪。`,
      partial: (loaded, total) => `父代详细基因部分加载完成 · ${loaded} / ${total} 已就绪。`,
      retry: '重试',
    },
    contributionTable: {
      ariaLabel: '预期后代基因贡献表',
      gene: '基因',
      source: '来源',
      balance: '平衡值',
      tooltipExpected: (value) => `预期值：${value}`,
      tooltipParent: ({ parent, value, weight, score, normalized }) => `${parent}：数值 ${value} · 权重 ${weight} · 分数 ${score} · 归一化 ${normalized}`,
      tooltipResult: (result) => `结果：${result}`,
    },
    compactGeneLabels: {
      unknownAxis: '性格',
      density: '密度',
      rhythmActivity: '节奏',
      dynamicLevel: '力度',
      register: '音区',
      polyphony: '织体',
      pitchRange: '音域',
    },
  },
  creativeBasket: {
    title: '创作篮',
    subtitle: '用于探索与重组的种子收藏区。',
    open: (count) => `创作篮 ${count}`,
    sectionTitles: {
      interesting: '感兴趣的种子',
      good: '喜欢的种子',
      mix: '已选种子',
    },
    empty: {
      interesting: '暂无感兴趣的种子。',
      good: '暂无喜欢的种子。',
      mix: '尚未选择用于混合的种子。',
    },
    actions: {
      addToMix: '加入混合',
      removeFromMix: '移出混合',
      removeMark: '取消标记',
      play: '播放',
      pause: '暂停',
    },
    badges: {
      interesting: '感兴趣',
      good: '喜欢',
      mix: '混合',
      generated: '后代',
      selected: '已选',
      playing: '播放中',
    },
    summaryLabels: {
      density: '密度',
      register: '音区',
      rhythm: '节奏',
      dynamic: '力度',
      chords: '和弦',
    },
    summaryEmpty: '暂无概要信息。',
  },
  familyTree: {
    title: '创作族谱',
    subtitle: '展示后代与父代种子的关系。',
    open: (count) => `创作族谱 ${count}`,
    emptyTitle: '暂无后代',
    emptyHint: '混合几个种子，开始培育你的创作族谱。',
    generation: (depth) => `第 ${depth} 代`,
    actions: {
      play: '播放',
      pause: '暂停',
      addToMix: '加入混合',
      removeFromMix: '移出混合',
      clear: '清空族谱',
      clearConfirm: '确定清空整个创作族谱吗？',
    },
    badges: {
      source: '父代种子',
      generated: '后代',
      mix: (index) => `混合 #${index}`,
      selected: '已选',
      playing: '播放中',
      interesting: '感兴趣',
      good: '喜欢',
      reused: '复用',
      crossTree: '跨分支混合',
    },
    tabs: {
      ariaLabel: '创作族谱',
      mixCount: (count) => `${count} 次混合`,
      generationCount: (count) => `${count} 代`,
      crossTree: '跨分支',
    },
    labels: {
      bars: '小节',
      bpm: 'BPM',
      chords: '和弦',
      density: '密度',
      register: '音区',
      rhythm: '节奏',
      dynamic: '力度',
    },
  },
  gene: {
    button: '基因',
    open: '打开音乐基因面板',
    title: '音乐基因',
    subtitle: (rank) => `种子 #${rank}`,
    geneIdPending: '基因分析等待中',
    moodTags: '情绪标签',
    dnaTitle: 'DNA 特征',
    dnaHint: '悬停查看基因位点',
    dnaAriaLabel: '音乐基因 DNA 特征',
    lociTitle: '基因位点',
    harmonyTitle: '和声链',
    noChords: '暂无和弦信息',
    basicTitle: '基础信息',
    empty: '请选择一个种子查看其音乐基因。',
    profileStatus: {
      noGeneProfileId: '暂无详细基因分析，显示概要信息。',
      loading: '正在加载详细基因...',
      error: '详细基因加载失败，显示概要信息。',
      loaded: (version) => `详细基因已加载 · ${version || '未知版本'}`,
      loadedMeta: (midi, config) => `MIDI：${midi} · 配置：${config}`,
      summary: '仅显示概要信息。',
    },
    basicRows: {
      duration: '时长',
      tempo: '速度',
      meter: '拍号',
      bars: '小节',
      tracks: '轨道',
      programs: '音色',
      pitchedNotes: '有音高音符',
      drums: '鼓组',
      secondsUnit: '秒',
      bpmUnit: 'BPM',
      warnings: (count) => `${count} 个警告`,
    },
    harmonyMeta: {
      mixSettingsSource: '来源：混合设置中的和弦进行',
      provider: (provider, status, unique, unknown) => `来源：${provider || '-'} · 状态：${status || '-'} · 不同和弦数：${unique ?? '-'} · 未识别：${unknown}`,
      bar: (index) => `第 ${index} 小节`,
    },
    loci: {
      summaryFallback: '概要信息',
      source: (source) => `来源：${source}`,
    },
  },
  panels: {
    close: '关闭',
    advancedTitle: '高级设置',
    debugTitle: '调试',
    themeTitle: '主题',
  },
  advanced: {
    labels: {
      baseUrl: 'BASE_URL',
      poolId: 'pool_id',
      topK: 'top_k',
      selectN: 'select_n',
      axes: 'axes',
      endpointNList: 'endpoint_n_list',
      pollingInterval: '轮询间隔 ms',
      showAxisFrames: '在地图外侧显示 X/Y 轴标签',
    },
    save: '保存',
    resetLocalState: '重置本地状态',
  },
  debug: {
    tabs: {
      task: '任务',
      space: '空间',
      artifacts: '资源',
      requests: '请求',
      events: '事件',
    },
    emptyTask: '暂无任务。',
    emptySpace: '暂无空间。',
    emptyArtifacts: '暂无资源。',
    metadata: '元数据',
    content: '内容',
  },
  theme: {
    options: [
      { id: 'theme-nord', label: '北境极光' },
      { id: 'theme-dark', label: '深夜黑曜' },
      { id: 'theme-minimal', label: '极简冰川' },
    ],
  },
  errors: {
    audioUnavailable: '音频不可用或加载失败。',
    missingAudioUrl: '该种子没有音频地址。',
    audioPlayFailed: '音频播放失败。',
    taskFailed: '任务执行失败',
    missingSpaceId: '任务完成但未返回空间ID',
    taskPollingTimeout: (maxAttempts) => `任务轮询超时，已尝试 ${maxAttempts} 次`,
    maxMixCandidates: '最多只能选择 3 个种子进行混合。',
    mixNeedsTwo: '至少选择 2 个种子才能生成后代。',
    missingMixContext: '缺少工作空间或种子空间，无法生成后代。',
    mixFailed: '混合任务失败',
    chordCount: (current, target) => `和弦数量需要等于小节数：当前 ${current} 个，目标 ${target} 个。`,
    invalidChord: (chord) => `和弦格式不合理：${chord}`,
  },
};
