export const uiText = {
  app: {
    fatalErrorTitle: 'Application error',
  },
  topBanner: {
    defaultQuery: 'quiet dreamy piano loop',
    title: 'Music Seed Space',
    subtitle: 'seed-space exploration HUD',
    queryPlaceholder: 'Describe a music idea...',
    search: 'Search',
    candidateCount: (count) => `${count} seeds`,
    noPair: 'no pair',
    noQuery: 'no query',
    resetView: 'Reset view',
    toggleHud: 'Toggle HUD',
    advanced: '',
    theme: '',
    debug: '',
  },
  map: {
    emptyTitle: 'Enter a query to generate a seed space.',
    emptyHint: 'WASD or arrow keys move the camera. Mouse wheel zooms.',
    loadingQueued: '任务排队中',
    loadingRunning: '正在分析种子空间与生成坐标轴说明…',
    showAxisNote: '显示坐标轴说明',
    hideAxisNote: '隐藏坐标轴说明',
    showHud: 'HUD',
    minimapTitle: 'MiniMap',
    minimapAria: 'Seed minimap',
  },
  axisFallbacks: {
    xName: '明亮感',
    yName: '張力感',
    xNegative: '陰暗厚重',
    xPositive: '明亮輕盈',
    yNegative: '柔和治癒',
    yPositive: '緊張強烈',
  },
  candidate: {
    generatedMix: 'Offspring',
    title: (rank) => `Seed #${rank}`,
    offspringTitle: (rank) => `Offspring #${rank}`,
    shortTitle: (id) => `Seed ${id}`,
    offspringShortTitle: (id) => `Offspring ${id}`,
    ariaLabel: (rank) => `Seed ${rank}`,
    offspringAriaLabel: (rank) => `Offspring ${rank}`,
    untagged: 'untagged',
    tooltipHint: 'click to inspect',
    details: 'Seed Details',
    previous: 'Previous',
    next: 'Next',
    playPause: 'Play or pause',
    volume: 'Playback volume',
    marks: {
      good: '👍',
      bad: '👎',
      interesting: '❤️',
    },
    downloadMidi: 'Download MIDI',
    midi: 'MIDI',
    fields: {
      candidateId: 'candidate_id',
      rank: 'rank',
      searchScore: 'search_score',
      poolId: 'pool_id',
      embeddingIndex: 'embedding_index',
      pcValues: 'pc_values',
      audioUrl: 'audio_url',
      midiUrl: 'midi_url',
      parentCandidateIds: 'parent_candidate_ids',
      mixId: 'mix_id',
      createdByTaskId: 'created_by_task_id',
    },
  },
  mixing: {
    title: 'Seed Mix',
    open: 'Mix Selected',
    generate: 'Generate Mix',
    generating: '正在生成新的混合片段…',
    clear: 'Clear',
    remove: 'Remove',
    emptyHint: '按住 Ctrl 或 Cmd 点击地图上的种子，加入 Mixing。至少选择 2 个种子才能生成混合。',
    sources: 'Selected Seeds',
    geometry: 'Blend point',
    geometryHint: '拖动调整比例，滚轮缩放',
    weights: 'Weights',
    settings: 'Settings',
    outputBars: '小节数',
    targetBpm: 'BPM',
    chordProgression: '和弦行进（用逗号分隔，每小节一个）',
    defaultChordProgression: ['C', 'Am', 'F', 'G'],
    chordValid: '和弦行进可用。',
    bpmError: 'BPM 需要在 40 到 240 之间。',
    geneSynthesisTitle: 'Gene Synthesis',
    expectedGenomeTitle: 'Expected Offspring Genome',
    harmonySourcesTitle: 'Harmony Sources',
    harmonyPreviewHint: 'Harmony is sequence-based and will be resolved during generation.',
    parentGenomeStatus: {
      loaded: 'Detailed genome ready',
      loading: 'Loading detailed genome...',
      error: 'Summary genome fallback',
      summary: 'Summary genome',
    },
    synthesisStatus: {
      summary: 'Summary-level genome preview.',
      error: 'Some profiles failed. Showing best available genome data.',
      loaded: 'Detailed parent genomes loaded.',
      loading: (loaded, total) => `Loading detailed parent genomes... ${loaded} / ${total} ready.`,
      partial: (loaded, total) => `Detailed genomes partially loaded · ${loaded} / ${total} ready.`,
      retry: 'Retry',
    },
    contributionTable: {
      ariaLabel: 'Expected offspring genome contribution table',
      gene: 'Gene',
      source: 'Source',
      balance: 'balance',
      tooltipExpected: (value) => `Expected: ${value}`,
      tooltipParent: ({ parent, value, weight, score, normalized }) => `${parent}: value ${value} · weight ${weight} · score ${score} · normalized ${normalized}`,
      tooltipResult: (result) => `Result: ${result}`,
    },
    compactGeneLabels: {
      unknownAxis: '性格',
      density: '密度',
      rhythmActivity: '节奏',
      dynamicLevel: '力度',
      register: '音区',
      polyphony: '织体',
      pitchRange: '音域',
    },
  },
  creativeBasket: {
    title: 'Creative Basket',
    subtitle: 'Collected seeds for exploration and recombination.',
    open: (count) => `Creative Basket · ${count}`,
    sectionTitles: {
      interesting: 'Interesting Seeds',
      good: 'Good Seeds',
      mix: 'Selected Seeds',
    },
    empty: {
      interesting: 'No interesting seeds yet.',
      good: 'No good seeds yet.',
      mix: 'No seeds selected for mixing.',
    },
    actions: {
      addToMix: 'Add to Mix',
      removeFromMix: 'Remove from Mix',
      removeMark: 'Remove Mark',
      play: 'Play',
      pause: 'Pause',
    },
    badges: {
      interesting: 'Interesting',
      good: 'Good',
      mix: 'Mix',
      generated: 'Offspring',
      selected: 'Selected',
      playing: 'Playing',
    },
    summaryLabels: {
      density: 'Density',
      register: 'Register',
      rhythm: 'Rhythm',
      dynamic: 'Dynamic',
      chords: 'Chords',
    },
    summaryEmpty: 'Summary not available.',
  },
  familyTree: {
    title: 'Creative Family Tree',
    subtitle: 'Offspring and their parent seed relationships.',
    open: (count) => `Creative Family Tree · ${count}`,
    emptyTitle: 'No offspring yet.',
    emptyHint: 'Mix a few seeds to start growing your family tree.',
    generation: (depth) => `Gen ${depth}`,
    actions: {
      play: 'Play',
      pause: 'Pause',
      addToMix: 'Add to Mix',
      removeFromMix: 'Remove from Mix',
      clear: 'Clear Tree',
      clearConfirm: 'Clear the entire creative family tree?',
    },
    badges: {
      source: 'Parent Seed',
      generated: 'Offspring',
      mix: (index) => `Mix #${index}`,
      selected: 'Selected',
      playing: 'Playing',
      interesting: 'Interesting',
      good: 'Good',
      reused: 'reused',
      crossTree: 'Cross-tree mix',
    },
    tabs: {
      ariaLabel: 'Creative family trees',
      mixCount: (count) => `${count} ${count === 1 ? 'mix' : 'mixes'}`,
      generationCount: (count) => `${count} gens`,
      crossTree: 'Cross-tree',
    },
    labels: {
      bars: 'Bars',
      bpm: 'BPM',
      chords: 'Chords',
      density: 'Density',
      register: 'Register',
      rhythm: 'Rhythm',
      dynamic: 'Dynamic',
    },
  },
  gene: {
    button: 'Gene',
    open: 'Open Music Genome Panel',
    title: 'Music Genome',
    subtitle: (rank) => `Seed #${rank}`,
    geneIdPending: 'gene profile pending',
    moodTags: 'Mood Tags',
    dnaTitle: 'DNA Keys',
    dnaHint: 'hover a key to inspect its locus',
    dnaAriaLabel: 'Music genome DNA keys',
    lociTitle: 'Gene Loci',
    harmonyTitle: 'Harmony Chain',
    noChords: 'No chord summary available.',
    basicTitle: 'Basic Info',
    empty: 'Select a seed to inspect its music genome.',
    profileStatus: {
      noGeneProfileId: 'No gene profile id. Showing summary-level genome.',
      loading: 'Loading detailed profile...',
      error: 'Could not load detailed profile. Showing summary-level genome.',
      loaded: (version) => `Detailed profile loaded · ${version || 'unknown version'}`,
      loadedMeta: (midi, config) => `midi: ${midi} · config: ${config}`,
      summary: 'Summary preview only.',
    },
    basicRows: {
      duration: 'Duration',
      tempo: 'Tempo',
      meter: 'Meter',
      bars: 'Bars',
      tracks: 'Tracks',
      programs: 'Programs',
      pitchedNotes: 'Pitched notes',
      drums: 'Drums',
      secondsUnit: 'sec',
      bpmUnit: 'BPM',
      warnings: (count) => `${count} warning(s)`,
    },
    harmonyMeta: {
      mixSettingsSource: 'source: mix settings chord progression',
      provider: (provider, status, unique, unknown) => `provider: ${provider || '-'} · status: ${status || '-'} · unique chords: ${unique ?? '-'} · unknown: ${unknown}`,
      bar: (index) => `Bar ${index}`,
    },
    loci: {
      summaryFallback: 'summary fallback',
      source: (source) => `source: ${source}`,
    },
  },
  panels: {
    close: 'Close',
    advancedTitle: 'Advanced',
    debugTitle: 'Debug',
    themeTitle: 'Theme',
  },
  advanced: {
    labels: {
      baseUrl: 'BASE_URL',
      poolId: 'pool_id',
      topK: 'top_k',
      selectN: 'select_n',
      axes: 'axes',
      endpointNList: 'endpoint_n_list',
      pollingInterval: 'polling interval ms',
      showAxisFrames: 'Show X/Y axis labels outside map',
    },
    save: 'Save',
    resetLocalState: 'Reset local state',
  },
  debug: {
    tabs: {
      task: 'task',
      space: 'space',
      artifacts: 'artifacts',
      requests: 'requests',
      events: 'events',
    },
    emptyTask: 'No task yet.',
    emptySpace: 'No space yet.',
    emptyArtifacts: 'No artifacts.',
    metadata: 'Metadata',
    content: 'Content',
  },
  theme: {
    options: [
      { id: 'theme-nord', label: 'Nord Frost' },
      { id: 'theme-dark', label: 'Deep Dark' },
      { id: 'theme-minimal', label: 'Minimal Ice' },
    ],
  },
  errors: {
    audioUnavailable: 'Audio unavailable or failed to load.',
    missingAudioUrl: 'This seed has no audio_url.',
    audioPlayFailed: 'Audio failed to play.',
    taskFailed: 'Task failed',
    missingSpaceId: 'Task finished without outputs.space_id',
    taskPollingTimeout: (maxAttempts) => `Task polling timed out after ${maxAttempts} attempts`,
    maxMixCandidates: '最多只能选择 3 个种子进行混合。',
    mixNeedsTwo: '至少选择 2 个种子才能生成混合。',
    missingMixContext: '缺少 workspace 或 space，无法生成混合。',
    mixFailed: 'Mix task failed',
    chordCount: (current, target) => `和弦数量需要等于小节数：当前 ${current} 个，目标 ${target} 个。`,
    invalidChord: (chord) => `和弦格式不合理：${chord}`,
  },
};
